// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO CUSTOMERS (name, phone_number, address) VALUES ($1, $2, $3) returning id, name, phone_number, address
`

type CreateCustomerParams struct {
	Name        string      `json:"name"`
	PhoneNumber string      `json:"phone_number"`
	Address     pgtype.Text `json:"address"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.PhoneNumber, arg.Address)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Address,
	)
	return i, err
}

const getCustomerByName = `-- name: GetCustomerByName :one
SELECT id, name, phone_number, address FROM CUSTOMERS WHERE name ILIKE $1
`

func (q *Queries) GetCustomerByName(ctx context.Context, name string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByName, name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Address,
	)
	return i, err
}
