// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const itemCreate = `-- name: ItemCreate :one
INSERT INTO items (name, price) VALUES ($1, $2) RETURNING id, name, price
`

type ItemCreateParams struct {
	Name  string         `json:"name"`
	Price pgtype.Numeric `json:"price"`
}

func (q *Queries) ItemCreate(ctx context.Context, arg ItemCreateParams) (Item, error) {
	row := q.db.QueryRow(ctx, itemCreate, arg.Name, arg.Price)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.Price)
	return i, err
}

const itemDelete = `-- name: ItemDelete :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) ItemDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, itemDelete, id)
	return err
}

const itemList = `-- name: ItemList :many
SELECT id, name, price FROM items
`

func (q *Queries) ItemList(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, itemList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itemUpdate = `-- name: ItemUpdate :one
UPDATE items SET name = $1, price = $2 WHERE id = $3 RETURNING id, name, price
`

type ItemUpdateParams struct {
	Name  string         `json:"name"`
	Price pgtype.Numeric `json:"price"`
	ID    uuid.UUID      `json:"id"`
}

func (q *Queries) ItemUpdate(ctx context.Context, arg ItemUpdateParams) (Item, error) {
	row := q.db.QueryRow(ctx, itemUpdate, arg.Name, arg.Price, arg.ID)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.Price)
	return i, err
}
