// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, price) VALUES ($1, $2) RETURNING id, name, price
`

type CreateItemParams struct {
	Name  string         `json:"name"`
	Price pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.Name, arg.Price)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.Price)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, name, price FROM items
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items SET name = $1, price = $2 WHERE id = $3 RETURNING id, name, price
`

type UpdateItemParams struct {
	Name  string         `json:"name"`
	Price pgtype.Numeric `json:"price"`
	ID    pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem, arg.Name, arg.Price, arg.ID)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.Price)
	return i, err
}
