// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const userCreate = `-- name: UserCreate :one
insert into users (username, password) values ($1, $2) returning id, username, password
`

type UserCreateParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.Username, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const userGetByUsername = `-- name: UserGetByUsername :one
select id, username, password from users where username = $1
`

func (q *Queries) UserGetByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const userList = `-- name: UserList :many
select id, username, password from users
`

func (q *Queries) UserList(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, userList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Username, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userPasswordReset = `-- name: UserPasswordReset :one
update users set password = $1 where id = $2 returning id, username, password
`

type UserPasswordResetParams struct {
	Password string    `json:"password"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UserPasswordReset(ctx context.Context, arg UserPasswordResetParams) (User, error) {
	row := q.db.QueryRow(ctx, userPasswordReset, arg.Password, arg.ID)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}
